spring:
  cloud:
    stream:
      kafka:
        binder:
          brokers: localhost
  zipkin:
    sender:
      type: kafka
  sleuth:
    sampler:
      rate: 10
      probability: 1.0
#Setting logging levels
logging:
  level:
    com.netflix: INFO
    org.springframework.web: INFO
    com.learn: DEBUG
server:
  port: 5080
