spring:
  cloud:
    stream:
      bindings:
        outboundOrg:
          destination: orgChangeTopic
          content-type: application/json
          group: licensingGroup
      kafka:
        binder:
          brokers: localhost


#        input:
#          destination: orgChangeTopic
#          content-type: application/json
#          group: licensingGroup

#eureka:
#  instance:
#    preferIpAddress: true
#  client:
#    defaultZone: http://localhost:8761/eureka/
#    registerWithEureka: true
#    fetchRegistry: true
#    serviceUrl:

#Setting logging levels
logging:
  level:
    com.netflix: INFO
    org.springframework.web: INFO
    com.learn: DEBUG

