spring:
  zipkin:
    service:
      name: zipkin-server-demo
  application:
    name: sleuth-zipkin-server
  cloud:
    stream:
      kafka:
        binder:
          brokers: localhost
server:
  port: 9411